version: "3.5"
services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    container_name: postgres
    restart: on-failure
    env_file:
      - ${SCRIPTPATH}/.env
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD:-postgres}
    networks:
      - default
    profiles:
      - event-replay
      - stacks-blockchain
  stacks-blockchain:
    image: ceramicwhite/stacks-blockchain:v2.05.0.2.2@sha256:8420a2af59701875eddcd4d4d694d13268744fc819f9763170d14d652fa5a6ca
    container_name: stacks-blockchain
    restart: on-failure
    ports:
      - ${STACKS_CORE_RPC_PORT:-20443}:${STACKS_CORE_RPC_PORT:-20443}
      - ${STACKS_CORE_P2P_PORT:-20444}:${STACKS_CORE_P2P_PORT:-20444}
    env_file:
      - ${SCRIPTPATH}/.env
    networks:
      - default
    depends_on:
      - stacks-blockchain-api
    profiles:
      - stacks-blockchain
    command:
      [
        "/bin/stacks-node",
        "start",
        "--config",
        "/src/stacks-blockchain/Config.toml",
      ]
  stacks-blockchain-api:
    image: ceramicwhite/stacks-blockchain-api:v4.1.0@sha256:dc2091682ff5ab6127c492da3c9eb9a1cc24b3cea3b2fc97f2807982b3c3f403
    container_name: stacks-blockchain-api
    restart: always
    ports:
      - ${STACKS_BLOCKCHAIN_API_PORT:-3999}:${STACKS_BLOCKCHAIN_API_PORT:-3999}
    env_file:
      - ${SCRIPTPATH}/.env
    networks:
      - default
    depends_on:
      - postgres
    profiles:
      - event-replay
      - stacks-blockchain
    command: ["npm", "run", "start"]
networks:
  default:
    name: ${DOCKER_NETWORK}
    ipam:
      driver: default
